#!/usr/bin/env python3

import json
import posixpath
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from zipfile import ZipFile


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "实验室网站文本内容收集.xlsx"

NS = {
    "m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
    "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    "rel": "http://schemas.openxmlformats.org/package/2006/relationships",
    "xdr": "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    "a": "http://schemas.openxmlformats.org/drawingml/2006/main",
}

GENERATED_HEADER = "\n".join(
    [
        "// This file is generated by scripts/sync-local-sheet.py.",
        "// Do not edit by hand; update 实验室网站文本内容收集.xlsx and rerun `npm run sync:sheet`.",
    ]
)

STATIC_TEXT_MAP = {
    "主页页眉": ("home", "siteLabel"),
    "主页主标题": ("home", "labName"),
    "主页副标题": ("home", "heroDesc"),
    "主页跳转按钮1": ("home", "seeResearch"),
    "主页跳转按钮2": ("home", "meetPeople"),
    "主页跳转按钮3": ("home", "latestNewsLink"),
    "主页跳转按钮4": ("home", "contactUs"),
    "研究模块页眉": ("home", "featured"),
    "研究模块标题": ("home", "focusAreas"),
    "合作模块页眉": ("home", "partnerEyebrow"),
    "合作模块标题": ("home", "partnerTitle"),
    "底页小标题": ("app", "groupName"),
    "底页大标题": ("app", "footerHeadline"),
    "成员页页眉": ("people", "eyebrow"),
    "成员页标题": ("people", "title"),
    "成员页副标题": ("people", "subtitle"),
    "成员页教师标题": ("people", "sectionTitles.Faculty"),
    "成员页博士生标题": ("people", "sectionTitles.PhD"),
    "成员页硕士生标题": ("people", "sectionTitles.Master"),
    "成员页本科生标题": ("people", "sectionTitles.Undergrads"),
    "成员页毕业生标题": ("people", "sectionTitles.Alumni"),
    "研究页页眉": ("research", "eyebrow"),
    "研究页标题": ("research", "title"),
    "研究页副标题": ("research", "subtitle"),
    "新闻页页眉": ("news", "eyebrow"),
    "新闻页标题": ("news", "title"),
    "新闻页副标题": ("news", "subtitle"),
    "联系页页眉": ("contact", "eyebrow"),
    "联系页标题": ("contact", "title"),
    "联系页副标题": ("contact", "subtitle"),
}

GRADE_TO_SECTION = {
    "教师": "Faculty",
    "faculty": "Faculty",
    "博士生": "PhD",
    "phd": "PhD",
    "phd students": "PhD",
    "硕士生": "Master",
    "master": "Master",
    "master students": "Master",
    "本科生": "Undergrads",
    "undergrad": "Undergrads",
    "undergrads": "Undergrads",
    "undergraduate students": "Undergrads",
    "毕业生": "Alumni",
    "alumni": "Alumni",
}

SECTION_ORDER = ["Faculty", "PhD", "Master", "Undergrads", "Alumni"]

KNOWN_TAGS = {
    "differentiable-memory",
    "higher-level-lm",
    "latent-ponder",
    "gfn-rl",
    "efficient-lm",
    "graph-learning",
}


def warn(message):
    print(f"[sync-local-sheet] warning: {message}", file=sys.stderr)


def col_to_index(cell_ref):
    letters = "".join(ch for ch in cell_ref if ch.isalpha())
    value = 0
    for ch in letters:
        value = value * 26 + ord(ch.upper()) - 64
    return value - 1


def read_relationships(zip_file, name):
    try:
        root = ET.fromstring(zip_file.read(name))
    except KeyError:
        return {}

    return {
        rel.get("Id"): rel.get("Target")
        for rel in root.findall("rel:Relationship", NS)
    }


def shared_string_text(node):
    return "".join(text.text or "" for text in node.findall(".//m:t", NS))


def read_shared_strings(zip_file):
    try:
        root = ET.fromstring(zip_file.read("xl/sharedStrings.xml"))
    except KeyError:
        return []

    return [shared_string_text(item) for item in root.findall("m:si", NS)]


def cell_text(cell, shared_strings):
    cell_type = cell.get("t")
    if cell_type == "s":
        value = cell.find("m:v", NS)
        if value is None or value.text is None:
            return ""
        return shared_strings[int(value.text)]

    if cell_type == "inlineStr":
        return "".join(text.text or "" for text in cell.findall(".//m:t", NS))

    value = cell.find("m:v", NS)
    return value.text if value is not None and value.text is not None else ""


def normalize_zip_path(path):
    return posixpath.normpath(path).lstrip("/")


def resolve_zip_path(base, target):
    return normalize_zip_path(posixpath.join(posixpath.dirname(base), target))


def read_sheets(zip_file):
    shared_strings = read_shared_strings(zip_file)
    workbook = ET.fromstring(zip_file.read("xl/workbook.xml"))
    workbook_rels = read_relationships(zip_file, "xl/_rels/workbook.xml.rels")
    sheets = {}

    for sheet in workbook.findall(".//m:sheet", NS):
        rel_id = sheet.get(f"{{{NS['r']}}}id")
        target = workbook_rels[rel_id]
        sheet_path = normalize_zip_path(posixpath.join("xl", target))
        sheets[sheet.get("name")] = read_sheet(zip_file, sheet_path, shared_strings)

    return sheets


def read_sheet(zip_file, sheet_path, shared_strings):
    root = ET.fromstring(zip_file.read(sheet_path))
    rel_path = (
        posixpath.dirname(sheet_path)
        + "/_rels/"
        + posixpath.basename(sheet_path)
        + ".rels"
    )
    rels = read_relationships(zip_file, rel_path)
    hyperlink_by_ref = {}

    for hyperlink in root.findall("m:hyperlinks/m:hyperlink", NS):
        ref = hyperlink.get("ref")
        rel_id = hyperlink.get(f"{{{NS['r']}}}id")
        if ref and rel_id in rels:
            hyperlink_by_ref[ref] = rels[rel_id]

    rows = {}
    for row in root.findall("m:sheetData/m:row", NS):
        row_index = int(row.get("r"))
        values = {}
        hyperlinks = {}
        for cell in row.findall("m:c", NS):
            ref = cell.get("r")
            col_index = col_to_index(ref)
            values[col_index] = cell_text(cell, shared_strings)
            if ref in hyperlink_by_ref:
                hyperlinks[col_index] = hyperlink_by_ref[ref]
        rows[row_index] = {"values": values, "hyperlinks": hyperlinks}

    drawing_path = None
    for target in rels.values():
        if "drawings/" in target:
            drawing_path = resolve_zip_path(sheet_path, target)
            break

    images = read_drawing_images(zip_file, drawing_path) if drawing_path else []
    return {"rows": rows, "images": images}


def read_drawing_images(zip_file, drawing_path):
    rel_path = (
        posixpath.dirname(drawing_path)
        + "/_rels/"
        + posixpath.basename(drawing_path)
        + ".rels"
    )
    rels = read_relationships(zip_file, rel_path)
    root = ET.fromstring(zip_file.read(drawing_path))
    images = []

    for anchor in list(root):
        from_node = anchor.find("xdr:from", NS)
        pic = anchor.find("xdr:pic", NS)
        if from_node is None or pic is None:
            continue

        row = int(from_node.find("xdr:row", NS).text) + 1
        col = int(from_node.find("xdr:col", NS).text) + 1
        blip = pic.find(".//a:blip", NS)
        rel_id = blip.get(f"{{{NS['r']}}}embed") if blip is not None else ""
        media_target = rels.get(rel_id)
        if not media_target:
            continue

        images.append(
            {
                "row": row,
                "col": col,
                "media": resolve_zip_path(drawing_path, media_target),
            }
        )

    return images


def row_cell(sheet, row_number, col_index, prefer_hyperlink=False):
    row = sheet["rows"].get(row_number, {})
    value = (row.get("values", {}).get(col_index) or "").strip()
    hyperlink = (row.get("hyperlinks", {}).get(col_index) or "").strip()
    if prefer_hyperlink and hyperlink:
        return hyperlink
    return value


def set_nested(target, path_text, value):
    cursor = target
    parts = path_text.split(".")
    for part in parts[:-1]:
        cursor = cursor.setdefault(part, {})
    cursor[parts[-1]] = value


def build_site_text(static_sheet):
    overrides = {"zh": {}, "en": {}}
    for row_number in sorted(static_sheet["rows"]):
        label = row_cell(static_sheet, row_number, 0)
        if label not in STATIC_TEXT_MAP:
            continue

        zh_value = row_cell(static_sheet, row_number, 4) or row_cell(
            static_sheet, row_number, 2
        )
        en_value = row_cell(static_sheet, row_number, 5) or row_cell(
            static_sheet, row_number, 3
        )
        page, key_path = STATIC_TEXT_MAP[label]

        if zh_value:
            overrides["zh"].setdefault(page, {})
            set_nested(overrides["zh"][page], key_path, zh_value)
        if en_value:
            overrides["en"].setdefault(page, {})
            set_nested(overrides["en"][page], key_path, en_value)

    return overrides


def normalize_id(value):
    text = str(value or "").strip()
    if re.fullmatch(r"\d+\.0", text):
        return text[:-2]
    return text


def normalize_url(value):
    text = str(value or "").strip()
    if not text or text == '""':
        return ""
    if re.match(r"^https?://", text, re.I):
        return text
    if re.match(r"^[a-z0-9.-]+\.[a-z]{2,}/", text, re.I):
        return f"https://{text}"
    return text


def safe_stem(value):
    stem = re.sub(r"[^A-Za-z0-9._-]+", "-", str(value).strip()).strip(".-")
    return stem or "image"


def image_extension(media_path):
    ext = Path(media_path).suffix.lower()
    if ext in {".jpeg", ".jpg"}:
        return ".jpg"
    if ext == ".png":
        return ".png"
    if ext == ".webp":
        return ".webp"
    return ext or ".jpg"


def image_extension_from_bytes(data, fallback):
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return ".png"
    if data.startswith(b"\xff\xd8"):
        return ".jpg"
    if data.startswith(b"RIFF") and data[8:12] == b"WEBP":
        return ".webp"
    return fallback


def copy_image(zip_file, media_path, destination_stem, destination_dir, clean_siblings=False):
    destination_dir.mkdir(parents=True, exist_ok=True)
    data = zip_file.read(media_path)
    extension = image_extension_from_bytes(data, image_extension(media_path))
    filename = f"{destination_stem}{extension}"
    destination = destination_dir / filename
    if clean_siblings:
        for ext in [".jpg", ".jpeg", ".png", ".webp"]:
            sibling = destination_dir / f"{destination_stem}{ext}"
            if sibling != destination and sibling.exists():
                sibling.unlink()
    destination.write_bytes(data)
    return destination


def existing_people_image(stem):
    directory = ROOT / "public/static/people"
    for ext in [".jpg", ".jpeg", ".png", ".webp"]:
        candidate = directory / f"{stem}{ext}"
        if candidate.exists():
            return candidate
    return None


def clean_stale_numeric_people_images(valid_stems):
    directory = ROOT / "public/static/people"
    if not directory.exists():
        return

    for image in directory.iterdir():
        if not image.is_file():
            continue
        if not re.fullmatch(r"\d+", image.stem):
            continue
        if image.stem in valid_stems:
            continue
        image.unlink()


def build_people(zip_file, people_sheet):
    images_by_row = {
        image["row"]: image
        for image in people_sheet["images"]
        if image["col"] == 4
    }
    data = {section: [] for section in SECTION_ORDER}
    generated_stems = set()

    start_row = None
    for row_number in sorted(people_sheet["rows"]):
        if "请在下方添加成员数据" in row_cell(people_sheet, row_number, 0):
            start_row = row_number + 1
            break
    if start_row is None:
        start_row = 5

    for row_number in sorted(people_sheet["rows"]):
        if row_number < start_row:
            continue

        member_id = normalize_id(row_cell(people_sheet, row_number, 0))
        name = row_cell(people_sheet, row_number, 1)
        grade = row_cell(people_sheet, row_number, 2)
        bio = row_cell(people_sheet, row_number, 4)
        homepage = normalize_url(row_cell(people_sheet, row_number, 5, True))

        if not member_id or not name:
            continue

        section = GRADE_TO_SECTION.get(grade) or GRADE_TO_SECTION.get(grade.lower())
        if not section:
            warn(f"Unknown grade for member {name}: {grade}; placed in Undergrads.")
            section = "Undergrads"

        stem = safe_stem(member_id)
        if stem != member_id:
            warn(f"Sanitized member id `{member_id}` to image stem `{stem}`.")
        generated_stems.add(stem)

        pic = ""
        image = images_by_row.get(row_number)
        if image:
            destination = copy_image(
                zip_file,
                image["media"],
                stem,
                ROOT / "public/static/people",
                clean_siblings=True,
            )
            pic = f"./static/people/{destination.name}"
        else:
            existing = existing_people_image(stem)
            if existing:
                pic = f"./static/people/{existing.name}"

        data[section].append(
            {
                "id": member_id,
                "name": name,
                "pic": pic,
                "bio": bio,
                "homepage": homepage,
            }
        )

    clean_stale_numeric_people_images(generated_stems)
    return data


def split_tags(value):
    tags = [
        tag.strip()
        for tag in re.split(r"[,，;；\s]+", str(value or ""))
        if tag.strip()
    ]
    seen = set()
    result = []
    for tag in tags:
        if tag in seen:
            continue
        seen.add(tag)
        if tag not in KNOWN_TAGS:
            warn(f"Ignored unknown publication tag: {tag}")
            continue
        result.append(tag)
    return result


def import_name(slug):
    parts = re.split(r"[^A-Za-z0-9]+", slug)
    name = "".join(part[:1].upper() + part[1:] for part in parts if part)
    return f"{name or 'Paper'}Image"


def existing_research_image(stem):
    directory = ROOT / "src/assets/research"
    for ext in [".jpg", ".jpeg", ".png", ".webp"]:
        candidate = directory / f"{stem}{ext}"
        if candidate.exists():
            return candidate
    return None


def build_publications(zip_file, publications_sheet):
    images_by_row = {
        image["row"]: image
        for image in publications_sheet["images"]
        if image["col"] == 5
    }
    publications = []

    start_row = None
    for row_number in sorted(publications_sheet["rows"]):
        if "请在下方添加论文" in row_cell(publications_sheet, row_number, 0):
            start_row = row_number + 1
            break
    if start_row is None:
        start_row = 19

    for row_number in sorted(publications_sheet["rows"]):
        if row_number < start_row:
            continue

        slug = row_cell(publications_sheet, row_number, 0)
        title = row_cell(publications_sheet, row_number, 1)
        authors = row_cell(publications_sheet, row_number, 2)
        if not slug or not title or not authors:
            continue

        stem = safe_stem(slug)
        image_path = ""
        image = images_by_row.get(row_number)
        if image:
            destination = copy_image(
                zip_file,
                image["media"],
                stem,
                ROOT / "src/assets/research",
            )
            image_path = destination
        else:
            image_path = existing_research_image(stem) or ""

        publications.append(
            {
                "id": slug,
                "title": title,
                "authors": authors,
                "venue": row_cell(publications_sheet, row_number, 3),
                "imagePath": str(image_path) if image_path else "",
                "pdf": normalize_url(row_cell(publications_sheet, row_number, 5, True)),
                "github": normalize_url(
                    row_cell(publications_sheet, row_number, 6, True)
                ),
                "huggingface": normalize_url(
                    row_cell(publications_sheet, row_number, 7, True)
                ),
                "homepage": normalize_url(
                    row_cell(publications_sheet, row_number, 8, True)
                ),
                "tagIds": split_tags(row_cell(publications_sheet, row_number, 9)),
                "abstract": row_cell(publications_sheet, row_number, 10),
            }
        )

    return publications


def js_string(value):
    return json.dumps(value, ensure_ascii=False)


def js_value(value):
    return json.dumps(value, ensure_ascii=False, indent=2)


def write_site_text(site_text):
    content = (
        f"{GENERATED_HEADER}\n\n"
        f"export const siteTextOverrides = {js_value(site_text)};\n"
    )
    (ROOT / "src/data/siteText.js").write_text(content, encoding="utf-8")


def write_people(people):
    content = (
        f"{GENERATED_HEADER}\n\n"
        f"export const peopleData = {js_value(people)};\n"
    )
    (ROOT / "src/data/people.js").write_text(content, encoding="utf-8")


def relative_src_import(path_text):
    path = Path(path_text)
    rel = path.relative_to(ROOT / "src").as_posix()
    return f"@/{rel}"


def write_publications(publications):
    imports = []
    import_by_path = {}
    for paper in publications:
        image_path = paper.get("imagePath")
        if not image_path:
            continue
        specifier = relative_src_import(image_path)
        if specifier not in import_by_path:
            import_by_path[specifier] = import_name(paper["id"])
            imports.append(f'import {import_by_path[specifier]} from "{specifier}";')

    objects = []
    for paper in publications:
        image_expr = '""'
        if paper.get("imagePath"):
            image_expr = import_by_path[relative_src_import(paper["imagePath"])]

        objects.append(
            "\n".join(
                [
                    "  {",
                    f"    id: {js_string(paper['id'])},",
                    f"    title: {js_string(paper['title'])},",
                    f"    authors: {js_string(paper['authors'])},",
                    f"    venue: {js_string(paper['venue'])},",
                    f"    image: {image_expr},",
                    f"    pdf: {js_string(paper['pdf'])},",
                    f"    github: {js_string(paper['github'])},",
                    f"    huggingface: {js_string(paper['huggingface'])},",
                    f"    homepage: {js_string(paper['homepage'])},",
                    f"    tagIds: {js_value(paper['tagIds']).replace(chr(10), chr(10) + '    ')},",
                    f"    abstract: {js_string(paper['abstract'])},",
                    "  }",
                ]
            )
        )

    content = ""
    if imports:
        content += "\n".join(imports) + "\n\n"
    content += f"{GENERATED_HEADER}\n\nexport const publications = [\n"
    content += ",\n".join(objects)
    content += "\n];\n"
    (ROOT / "src/data/publications.js").write_text(content, encoding="utf-8")


def main():
    if not WORKBOOK.exists():
        raise SystemExit(f"Workbook not found: {WORKBOOK}")

    with ZipFile(WORKBOOK) as zip_file:
        sheets = read_sheets(zip_file)
        required = ["网页主要文本", "成员页面", "研究和论文"]
        missing = [name for name in required if name not in sheets]
        if missing:
            raise SystemExit(f"Missing sheet(s): {', '.join(missing)}")

        site_text = build_site_text(sheets["网页主要文本"])
        people = build_people(zip_file, sheets["成员页面"])
        publications = build_publications(zip_file, sheets["研究和论文"])

    write_site_text(site_text)
    write_people(people)
    write_publications(publications)

    people_count = sum(len(items) for items in people.values())
    print(
        f"Synced {people_count} people and {len(publications)} publications from {WORKBOOK.name}."
    )


if __name__ == "__main__":
    main()
